### ISSUE TITLE
Empty Value

### ISSUE THREAD

**Issue by seihb** [tasmaniski/zend-current-route#1]
Only in the Application Module showes it right values.

**Comment by tasmaniski** [comment]
Can you please post your route config, only "routes" key in config?
Also, please copy/paste result of var_dump() in modules that doesn't works:

```
var_dump(
    $this->currentRoute()->getController(), $this->currentRoute()->getAction(),  
    $this->currentRoute()->getModule(), $this->currentRoute()->getRoute()
);
```

Thank you for response!

**Comment by seihb** [comment]
Skeleton Application config default, it's ok.

Modul Voting config:

```
'router' => array(
    'routes' => array(
        'voting' => array(
            'type' => 'Literal',
            'options' => array(
                'route' => '/voting',
                'defaults' => array(
                    '__NAMESPACE__' => 'Voting',
                    'controller' => 'Index',
                    'action' => 'index',
                ),
            ),
            'may_terminate' => true,
            'child_routes' => array(
                'controller-action' => array(
                    'type' => 'segment',
                    'options' => array(
                        'route' => '/:controller[/:action[/:id]]',
                        'constraints' => array(
                            'controller' => '[a-zA-Z][a-zA-Z0-9_-]*',
                            'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
                            'id' => '[0-9_-]*',
                        ),
                    ),
                ),
            ),
        ),
    ),
),
```

**Comment by tasmaniski** [comment]
Thanks for the config. There was the bug, but it's solved now :) 

Can you please do a **composer update** and try new version (1.0.2).
If everything is OK please confirm here and than we can close the issue. 

Thank you for the support!

**Comment by seihb** [comment]
After composer update i receive an error:  
[RuntimeException]  
Could not scan for classes inside "src/" which does not appear to be a file  
nor a folder

**Comment by tasmaniski** [comment]
Did you try fresh install with composer? 
I can not reproduce the error. 

What you have in your system to trigger that error? 
and are you sure that the error didn't related to some other package?

**Comment by seihb** [comment]
Thanks, with fresh install composer it works fine.

**Comment by tasmaniski** [comment]
I improved stability even more, so update fresh version once again (1.0.3). 

Thank you for debugging!
