### ISSUE TITLE
Laminas - requirements could not be resolved

### ISSUE THREAD

**Issue by MakorKa** [tasmaniski/zend-current-route#7]
Cant install with latest Laminas

`Problem 1
    - Conclusion: remove laminas/laminas-mvc 3.1.1
    - Conclusion: don't install laminas/laminas-mvc 3.1.1
    - tasmaniski/laminas-current-route 3.0.0 requires laminas/laminas-mvc 3.0.* -> satisfiable by laminas/laminas-mvc[3.0.1, 3.0.2, 3.0.3, 3.0.4].
    - tasmaniski/laminas-current-route 3.0.1 requires laminas/laminas-mvc 3.0.* -> satisfiable by laminas/laminas-mvc[3.0.1, 3.0.2, 3.0.3, 3.0.4].
    - tasmaniski/laminas-current-route 3.0.2 requires laminas/laminas-mvc 3.0.* -> satisfiable by laminas/laminas-mvc[3.0.1, 3.0.2, 3.0.3, 3.0.4].
    - Can only install one of: laminas/laminas-mvc[3.0.1, 3.1.1].
    - Can only install one of: laminas/laminas-mvc[3.0.2, 3.1.1].
    - Can only install one of: laminas/laminas-mvc[3.0.3, 3.1.1].
    - Can only install one of: laminas/laminas-mvc[3.0.4, 3.1.1].
    - Installation request for laminas/laminas-mvc (locked at 3.1.1, required as ^3.0.1) -> satisfiable by laminas/laminas-mvc[3.1.1].
    - Installation request for tasmaniski/laminas-current-route ^3.0 -> satisfiable by tasmaniski/laminas-current-route[3.0.0, 3.0.1, 3.0.2].

can you fix please? Thanks a lot )
`

**Comment by tasmaniski** [comment]
I solved it. Just add **dev-master**.
